name: Expo EAS Build and Upload APK Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: fishidentification/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: fishidentification

      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Build APK with EAS
        run: eas build --platform android --profile production --non-interactive
        working-directory: fishidentification
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Find Built APK
        id: find_apk
        run: |
          APK_PATH=$(find fishidentification -type f -name "*.apk" | sort -r | head -n 1)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: ${{ steps.find_apk.outputs.apk_path }}
